<?php

namespace AppBundle\Repository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCustomerAccounts()
    {
        return $this->createQueryBuilder('a')
            ->where('a.roles LIKE :roleCustomer')
            ->setParameter('roleCustomer', "%ROLE_CUSTOMER%")
            ->getQuery()
            ->getResult();
    }
}
