<?php

namespace AppBundle\Repository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
	public function findValidCardByNumber($number)
	{
		return $this->createQueryBuilder('c')
			->where('c.number = :number')
			->andWhere('c.isActive = true')
			->andWhere('c.customer IS NOT null')
			->setParameter('number', $number)
			->getQuery()
			->getOneOrNullResult()
			;


	}

    public function findInactiveCardByNumber($number)
    {
        return $this->createQueryBuilder('c')
            ->where('c.customer IS NULL')
            ->andWhere('c.isActive = false')
            ->andWhere('c.number = :number')
            ->setParameter("number", $number)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
