<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * CardOffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardOffersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findValidCardsOffersOfCustomer($card)
    {
        return $this->createQueryBuilder("co")
            ->innerJoin("co.offer", "o", Join::WITH, 'o.isActive = true')
            ->where('co.card = :card')
            ->setParameter("card", $card)
            ->getQuery()
            ->getResult();
    }
}
