<?php

namespace AppBundle\Repository;

/**
 * CardOffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardOffersRepository extends \Doctrine\ORM\EntityRepository
{
}
