<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCustomerWithoutCard($firstname, $lastname, $phone )
	{
		return $this->createQueryBuilder('c')
			->where('c.firstname = :firstname')
			->andWhere('c.lastname = :lastname')
			->andWhere('c.phone = :phone')
			->setParameters([
				'firstname' => $firstname,
				'lastname'  => $lastname,
				'phone'     => $phone
				])
			->getQuery()
			->getOneOrNullResult()
			;


	}

	public function findCustomerByCardNumber($number)
    {
        return $this->createQueryBuilder('c')
            ->innerJoin('c.card', 'ca', Join::WITH, 'ca.number = :number')
            ->setParameter('number', $number)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
