<?php

namespace AppBundle\Repository;

/**
 * GameSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
