<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * GameSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameSessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGameSessionsOfCustomer($card)
    {
        return $this->createQueryBuilder('gs')
            ->innerJoin('gs.cards', "c", Join::WITH, "c = :card")
            ->orderBy("gs.date", "DESC")
            ->setParameter("card", $card)
            ->getQuery()
            ->getResult();
    }
}
