<?php

namespace AppBundle\Repository;

/**
 * ResetPasswordTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResetPasswordTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
