
homepage:
    path: /
    defaults:
        _controller: AppBundle:Default:index
#SECURITY
register:
    path: /register
    defaults:
        _controller: AppBundle:Security:register

login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

logout:
    path: /logout




# CUSTOMER
customer_panel:
    path: /customer
    defaults:
        _controller: AppBundle:Customer:panel

customer_modify_infos:
    path: /customer/modify
    defaults:
        _controller: AppBundle:Customer:modify




# STAFF CARD MANAGEMENT

staff_search:
    path: /staff
    defaults:
        _controller: AppBundle:StaffCard:search

staff_card_view:
    path: /staff/card/{number}
    defaults:
        _controller: AppBundle:StaffCard:cardView
    requirements:
          number:     \d+

staff_edit_profile:
    path: /staff/card/{number}/editcustomer
    defaults:
           _controller: AppBundle:StaffCard:editCustomer
    requirements:
          number:     \d+

staff_edit_card:
    path: /staff/card/{number}/editcard
    defaults:
           _controller: AppBundle:StaffCard:editCard
    requirements:
          number:     \d+

staff_customer_offers_use:
    path: /staff/cardoffer/use/{id}
    defaults:
         _controller: AppBundle:StaffCard:useCardOffer

# STAFF NEWSLETTER MANAGEMENT

staff_newsletter_create:
    path: /staff/newsletter/create
    defaults:
        _controller: AppBundle:StaffNewsletter:create

staff_newsletter_list:
    path: /staff/newsletter/list
    defaults:
        _controller: AppBundle:StaffNewsletter:list

staff_newsletter_preview:
    path: /staff/newsletter/view/{id}
    defaults:
        _controller: AppBundle:StaffNewsletter:preview
    requirements:
        id: \d+

staff_newsletter_send:
    path: /staff/newsletter/send/{id}
    defaults:
        _controller: AppBundle:StaffNewsletter:send
    requirements:
        id: \d+

staff_newsletter_modify:
    path: /staff/newsletter/modify/{id}
    defaults:
        _controller: AppBundle:StaffNewsletter:modify
    requirements:
        id: \d+


# STAFF CREATE GAMESESSION


staff_gamesession:
    path: /staff/gamesession
    defaults:
        _controller: AppBundle:StaffGameSession:new

staff_autocomplete_customer_nickname_ajax:
    path: /staff/customer/{cardNumber}
    defaults:
        _controller: AppBundle:StaffGameSession:playerNameCompletionAjax

# STAFF OFFERS MANAGEMENT


staff_offers_list:
    path: /staff/offers/list
    defaults:
          _controller: AppBundle:StaffOffers:list

staff_offers_create:
    path: /staff/offers/new
    defaults:
          _controller: AppBundle:StaffOffers:create


staff_offers_active_ajax:
    path: /staff/offers/active/{id}
    defaults:
          _controller: AppBundle:StaffOffers:activeAjax


staff_offers_modify:
    path: /staff/offers/modify/{id}
    defaults:
          _controller: AppBundle:StaffOffers:modify

