fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


homepage:
    path: /
    defaults:
        _controller: AppBundle:Default:index


#SECURITY
register_staff:
    path: /super_staff
    defaults:
        _controller: AppBundle:Security:registerStaff

register:
    path: /register
    defaults:
        _controller: AppBundle:Security:register

login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

forgot_password:
    path: /forgot_password
    defaults:
        _controller: AppBundle:Security:forgotPassword

reset_password:
    path: /reset_password/{token}
    defaults:
        _controller: AppBundle:Security:resetPassword

logout:
    path: /logout

# CUSTOMER

customer_panel:
    path: /customer
    defaults:
        _controller: AppBundle:Customer:panel

customer_modify_infos:
    path: /customer/modify
    defaults:
        _controller: AppBundle:Customer:modify




# STAFF CUSTOMER MANAGEMENT

staff_search:
    path: /staff
    defaults:
        _controller: AppBundle:StaffCustomer:search

staff_customer_view:
    path: /staff/customer/{number}
    defaults:
        _controller: AppBundle:StaffCustomer:cardView
    requirements:
          number:     \d+

staff_edit_profile:
    path: /staff/customer/{number}/editcustomer
    defaults:
           _controller: AppBundle:StaffCustomer:editCustomer
    requirements:
          number:     \d+

staff_customer_offers_use:
    path: /staff/cardoffer/use/{id}
    defaults:
         _controller: AppBundle:StaffCustomer:useCardOffer

staff_customer_offers_use_temp:
    path: /staff/cardoffer/use/{offerid}/{cardid}
    defaults:
         _controller: AppBundle:StaffCustomer:useCardOfferTemp


# STAFF NEWSLETTER MANAGEMENT

staff_newsletter_create:
    path: /staff/newsletter/create
    defaults:
        _controller: AppBundle:StaffNewsletter:create

staff_newsletter_list:
    path: /staff/newsletter/list
    defaults:
        _controller: AppBundle:StaffNewsletter:list

staff_newsletter_preview:
    path: /staff/newsletter/view/{id}
    defaults:
        _controller: AppBundle:StaffNewsletter:preview
    requirements:
        id: \d+

staff_newsletter_send:
    path: /staff/newsletter/send/{id}
    defaults:
        _controller: AppBundle:StaffNewsletter:send
    requirements:
        id: \d+

staff_newsletter_modify:
    path: /staff/newsletter/modify/{id}
    defaults:
        _controller: AppBundle:StaffNewsletter:modify
    requirements:
        id: \d+

staff_newsletter_delete:
    path: /staff/newsletter/delete/{id}
    defaults:
        _controller: AppBundle:StaffNewsletter:delete
    requirements:
        id: \d+

# STAFF CREATE GAMESESSION


staff_gamesession:
    path: /staff/gamesession
    defaults:
        _controller: AppBundle:StaffGameSession:new

staff_autocomplete_customer_nickname_ajax:
    path: /staff/autocomplete-nickname/{cardNumber}
    defaults:
        _controller: AppBundle:StaffGameSession:playerNameCompletionAjax

# STAFF OFFERS MANAGEMENT


staff_offers_list:
    path: /staff/offers/list
    defaults:
          _controller: AppBundle:StaffOffers:list

staff_offers_create:
    path: /staff/offers/new
    defaults:
          _controller: AppBundle:StaffOffers:create


staff_offers_active_ajax:
    path: /staff/offers/active/{id}
    defaults:
          _controller: AppBundle:StaffOffers:activeAjax


staff_offers_modify:
    path: /staff/offers/modify/{id}
    defaults:
          _controller: AppBundle:StaffOffers:modify


# STAFF NEW CARD

staff_new_card:
    path: /staff/new-card
    defaults:
          _controller: AppBundle:StaffCard:new

staff_generate_new_card_ajax:
    path: /staff/new-card/generate/{center}
    defaults:
          _controller: AppBundle:StaffCard:generateAjax

staff_give_card_ajax:
    path: /staff/give-card/give/{id}
    defaults:
        _controller: AppBundle:StaffCard:giveCardAjax