app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path: /register
    defaults:
        _controller: AppBundle:Security:register

login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

logout:
    path: /logout

<<<<<<< HEAD
customer_panel:
    path: /customer
    defaults:
        _controller: AppBundle:Customer:panel

staff_panel:
    path: /staff
    defaults:
        _controller: AppBundle:Staff:panel
=======
staff:
    path: /staff
    defaults: { _controller: AppBundle:Staff:index }
>>>>>>> commit sans push
