app:
    resource: '@AppBundle/Controller/'
    type: annotation


#SECURITY
register:
    path: /register
    defaults:
        _controller: AppBundle:Security:register

login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

logout:
    path: /logout




# CUSTOMER
customer_panel:
    path: /customer
    defaults:
        _controller: AppBundle:Customer:panel

customer_modify_infos:
    path: /customer/modify
    defaults:
        _controller: AppBundle:Customer:modify




# STAFF

staff_panel:
    path: /staff
    defaults:
        _controller: AppBundle:Staff:panel

staff_card:
    path: /staff/card/{number}
    defaults:
        _controller: AppBundle:Staff:manageCard
    requirements:
          number:     \d+

staff_newsletter_create:
    path: /staff/newsletter/create
    defaults:
        _controller: AppBundle:Staff:newsletterCreate

staff_newsletter_list:
    path: /staff/newsletter/list
    defaults:
        _controller: AppBundle:Staff:newsletterList

staff_newsletter_preview:
    path: /staff/newsletter/view/{id}
    defaults:
        _controller: AppBundle:Staff:newsletterPreview
    requirements:
        id: \d+

staff_newsletter_send:
    path: /staff/newsletter/send/{id}
    defaults:
        _controller: AppBundle:Staff:newsletterSend
    requirements:
        id: \d+

staff_gamesession:
    path: /staff/gamesession
    defaults:
        _controller: AppBundle:Staff:newGameSession


staff_edit_profile:
    path: /staff/card/{number}/editcustomer
    defaults:
           _controller: AppBundle:Staff:editCustomer
    requirements:
          number:     \d+

staff_edit_card:
    path: /staff/card/{number}/editcard
    defaults:
           _controller: AppBundle:Staff:editCard
    requirements:
          number:     \d+

staff_customer_offers_use:
    path: /staff/cardoffer/use/{id}
    defaults:
         _controller: AppBundle:Staff:useCardOffer

staff_offers_list:
    path: /staff/offers/list
    defaults:
          _controller: AppBundle:Staff:offersList

staff_offers_create:
    path: /staff/offers/new
    defaults:
          _controller: AppBundle:Staff:offersCreate


staff_offers_active:
    path: /staff/offers/active/{id}
    defaults:
          _controller: AppBundle:Staff:offersActive


staff_offers_modify:
    path: /staff/offers/modify/{id}
    defaults:
          _controller: AppBundle:Staff:offersModify

