app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path: /register
    defaults:
        _controller: AppBundle:Security:register

login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

logout:
    path: /logout

customer_panel:
    path: /customer
    defaults:
        _controller: AppBundle:Customer:panel

customer_modify_infos:
    path: /customer/modify
    defaults:
        _controller: AppBundle:Customer:modify

staff_panel:
    path: /staff
    defaults:
        _controller: AppBundle:Staff:panel

staff_card:
    path: /staff/card/{number}
    defaults:
        _controller: AppBundle:Staff:manageCard
    requirements:
          number:     \d+

staff_newsletter:
    path: /staff/newsletter
    defaults:
        _controller: AppBundle:Staff:manageNewsletter

staff_offer:
    path: /staff/offer
    defaults:
        _controller: AppBundle:Staff:manageOffer


staff_gamesession:
    path: /staff/gamesession
    defaults:
        _controller: AppBundle:Staff:newGameSession






